import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sandeepchellappen' at '9/3/16 10:39 PM' with Gradle 2.13
 *
 * @author sandeepchellappen, @date 9/3/16 10:39 PM
 */
public class LibraryTest {
   
}
